language: cpp
os:
  - linux
dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-10
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j