language: cpp
os:
- linux
dist: focal
addons:
  apt:
    sources:
    - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
    - g++-10
  sonarcloud:
    organization: "volt-software"
    token:
      secure: "MShoxlExrqYoBpO0Za9L7clAyTmjp3MD/W8b7W7EtJnP8Sev8YceJV6fd6X5e9rBGpO0bRyTnizW1GHR2Znld6PVvYpxwsEAT1pwAJOGqfBVXF5Jd04WucNLStwe9KGOETBW+pAjuksAECFEg9KNGGVIYKeolr/A6czt/UeqX+J9z0uPHc7Im0/iard5UImymPGNsinrbDZq2uqqRSZaQdGOPBxlCrMXRSyW3WUJ1w6s8BBh7So5KB+vT/aan72xlgEMweSbDZmFHT/bxcpKA0omYfRyDC0BblfOjK/AQCxVQpg6CHYfiBKEfeMHvmUVzxxJEI+ZI+Rj5Psn+LOF9/zhIS9nxU/qalhLpwtAukrAcmjx0vem+YgAR4PgELbEBsJ7stJDfTwjLPnxBvpqZw7tku62o/16bS9qkfENigj5JaO6cg1ykmYqzF9Y5aEnHqB282bRy5Paxw4onMEpw8vxo1WXIuGvQ/57oR3nnaLMcn7yosqCHr8JckP/hBM1zthUrtQAPSz7CwFND1KZNohgCpYcxJQUzYedEc2lGMhUwNldRiepiFEMb1wzQxlECe4mPHcU0x2yu/DE+H6/cXtc+BXIIBq+JhTFx3K/VirxxbuY1lK4dP1pDL9LtXRhitb04PSNQypy3UX0kLF/KlnY8iLhoulfBuJm+gLW2Tk="

env:
  matrix:
  - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10 && SONARCLOUD=0 && EXTRA_OPTS=OFF"
  - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10 && SONARCLOUD=0 && EXTRA_OPTS=ON"
  - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10 && SONARCLOUD=1 && EXTRA_OPTS=OFF"

before_install:
- eval "${MATRIX_EVAL}"

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_SPDLOG=$EXTRA_OPTS -DUSE_LIBUV=$EXTRA_OPTS -DUSE_RAPIDJSON=$EXTRA_OPTS ..
- if [ "$SONARCLOUD" = "0" ]; then make -j2; fi
- if [ "$SONARCLOUD" = "1" ]; then cd .. && build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/ && sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.cfamily.threads=2; fi
