language: cpp
os:
  - linux
dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-10
env:
  - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j